### ISSUE TITLE
Meta Issue: Make issues for...

### ISSUE THREAD

**Issue by sastoudt** [sastoudt/reading-for-humanness#11]
- [ ] [The Memory Librarian](https://www.harpercollins.com/pages/the-memory-librarian)
- [ ] [Daughters of Earth](https://www.weslpress.org/9780819566768/daughters-of-earth/)
- [ ] [Strange Bedfellows: An anthology of Political Science Fiction](https://www.amazon.com/Strange-Bedfellows-Anthology-Political-Science/dp/1927881005)
- [ ] [Valleyesque](https://us.macmillan.com/books/9780374604141/valleyesque)
- [ ] [Out There](https://www.penguinrandomhouse.com/books/669018/out-there-by-kate-folk/)
- [ ] [Shit Cassandra Saw](https://www.penguinrandomhouse.com/books/671988/shit-cassandra-saw-by-gwen-e-kirby/)
- [ ] [Makers](https://en.wikipedia.org/wiki/Makers_(novel))
- [ ] [The Windup Girl](https://en.wikipedia.org/wiki/The_Windup_Girl)
- [ ] [Autonomous](https://en.wikipedia.org/wiki/Autonomous_(novel))
- [ ] [Radicalized](https://en.wikipedia.org/wiki/Radicalized_(Doctorow_book))
- [ ] [Walkaway](https://en.wikipedia.org/wiki/Walkaway_(Doctorow_novel))
- [ ] [Rainbow's End](https://en.wikipedia.org/wiki/Rainbows_End_(Vinge_novel))
- [ ] [Permutation City](https://en.wikipedia.org/wiki/Permutation_City)
